INSERT INTO MEMBER(LOGIN_ID, LOGIN_PASSWORD, NICKNAME) VALUES ("test", "test", "test");
INSERT INTO MEMBER(LOGIN_ID, LOGIN_PASSWORD, NICKNAME) VALUES ("test2", "test2", "test2");
INSERT INTO AMENITY(NAME) VALUES ("Air Conditioner");
INSERT INTO AMENITY(NAME) VALUES ("BBQ");
INSERT INTO AMENITY(NAME) VALUES ("CHULBONG");
INSERT INTO AMENITY(NAME) VALUES ("DARAKBANG");
INSERT INTO AMENITY(NAME) VALUES ("ENERGY DRINK");