DROP TABLE IF EXISTS ACCO_IMAGE;
DROP TABLE IF EXISTS ACCO_AMEN;
DROP TABLE IF EXISTS AMENITY;
DROP TABLE IF EXISTS ACCOMMODATION;
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE `MEMBER` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `LOGIN_ID` VARCHAR(50) NOT NULL,
    `LOGIN_PASSWORD` VARCHAR(200) NOT NULL,
    `NICKNAME` VARCHAR(50) NOT NULL
);

CREATE TABLE `ACCOMMODATION` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `HOST_ID` BIGINT,
    `TITLE` VARCHAR(50) NOT NULL,
    `PLACE_CATEGORY` VARCHAR(50) NOT NULL,
    `PRICE` BIGINT NOT NULL,
    `DESCRIPTION` VARCHAR(500),
    `MAX_GUEST` INT NOT NULL,
    `MAX_INFANT` INT NOT NULL,
    `BEDROOM_NUM` INT NOT NULL,
    `BED_NUM` INT NOT NULL,
    `BATHROOM_NUM` INT NOT NULL,
    `CHECK_IN_TIME` TIME NOT NULL DEFAULT "16:00:00",
    `CHECK_OUT_TIME` TIME NOT NULL DEFAULT "11:00:00",
    `COUNTRY` VARCHAR(2) NOT NULL,
    `PROVINCE` VARCHAR(100) NOT NULL,
    `CITY` VARCHAR(100),
    `DISTRICT` VARCHAR(100) NOT NULL,
    `STREET_ADDRESS` VARCHAR(100) NOT NULL,
    `STREET_ADDRESS_DETAIL` VARCHAR(100),
    `POSTAL_CODE` VARCHAR(50),
    `COORDINATE` POINT SRID 4326 NOT NULL
);

CREATE TABLE `AMENITY` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `NAME` VARCHAR(50) NOT NULL
);

CREATE TABLE `ACCO_AMEN` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ACCO_ID` BIGINT NOT NULL,
    `AMEN_ID` BIGINT NOT NULL
);

CREATE TABLE `ACCO_IMAGE` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ACCO_ID` BIGINT,
    `URL` VARCHAR(500) NOT NULL
);

ALTER TABLE `ACCO_AMEN` ADD FOREIGN KEY (`ACCO_ID`) REFERENCES `ACCOMMODATION` (`ID`);

ALTER TABLE `ACCO_AMEN` ADD FOREIGN KEY (`AMEN_ID`) REFERENCES `AMENITY` (`ID`);

ALTER TABLE `ACCOMMODATION` ADD FOREIGN KEY (`HOST_ID`) REFERENCES `MEMBER` (`ID`);

ALTER TABLE `ACCO_IMAGE` ADD FOREIGN KEY (`ACCO_ID`) REFERENCES `ACCOMMODATION` (`ID`);
