DROP TABLE IF EXISTS ACCO_PHOTO;
DROP TABLE IF EXISTS ACCOMMODATION;
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE `MEMBER` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `LOGIN_ID` VARCHAR(50) NOT NULL,
    `LOGIN_PASSWORD` VARCHAR(200) NOT NULL,
    `NICKNAME` VARCHAR(50) NOT NULL
);

CREATE TABLE `ACCOMMODATION` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `HOST_ID` BIGINT NOT NULL,
    `TITLE` VARCHAR(50) NOT NULL,
    `PLACE_CATEGORY` VARCHAR(50) NOT NULL,
    `PRICE` INT NOT NULL,
    `DESCRIPTION` VARCHAR(500),
    `MAX_GUEST` INT NOT NULL,
    `MAX_INFANT` INT NOT NULL,
    `BEDROOM_NUM` INT NOT NULL,
    `BED_NUM` INT NOT NULL,
    `BATHROOM_NUM` INT NOT NULL,
    `CHECK_IN_TIME` time NOT NULL DEFAULT "16:00:00",
    `CHECK_OUT_TIME` time NOT NULL DEFAULT "11:00:00",
    `COUNTRY` VARCHAR(2) NOT NULL,
    `PROVINCE` VARCHAR(100) NOT NULL,
    `CITY` VARCHAR(100),
    `DISTRICT` VARCHAR(100) NOT NULL,
    `STREET_ADDRESS` VARCHAR(100) NOT NULL,
    `STREET_ADDRESS_DETAIL` VARCHAR(100),
    `POSTAL_CODE` INT,
    `COORDINATE` POINT NOT NULL,
    `HAS_WIFI` TINYINT NOT NULL DEFAULT 0,
    `HAS_TV` TINYINT NOT NULL DEFAULT 0,
    `HAS_KITCHEN` TINYINT NOT NULL DEFAULT 0,
    `HAS_WASHER` TINYINT NOT NULL DEFAULT 0,
    `HAS_FREE_PARKING` TINYINT NOT NULL DEFAULT 0,
    `HAS_AIR_CONDITIONING` TINYINT NOT NULL DEFAULT 0,
    `HAS_WORKSPACE` TINYINT NOT NULL DEFAULT 0,
    `HAS_POOL` TINYINT NOT NULL DEFAULT 0,
    `HAS_BBQ` TINYINT NOT NULL DEFAULT 0,
    `HAS_GYM` TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE `ACCO_PHOTO` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ACCO_ID` BIGINT,
    `URL` VARCHAR(500) NOT NULL
);

ALTER TABLE `ACCOMMODATION` ADD FOREIGN KEY (`HOST_ID`) REFERENCES `MEMBER` (`ID`);

ALTER TABLE `ACCO_PHOTO` ADD FOREIGN KEY (`ACCO_ID`) REFERENCES `ACCOMMODATION` (`ID`);