DROP TABLE IF EXISTS RESERVATION_PRODUCT;
DROP TABLE IF EXISTS ACCO_PRODUCT;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS ACCO_IMAGE;
DROP TABLE IF EXISTS ACCO_AMEN;
DROP TABLE IF EXISTS AMENITY;
DROP TABLE IF EXISTS ACCOMMODATION;
DROP TABLE IF EXISTS OAUTH;
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE `MEMBER` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ACCOUNT_NAME` VARCHAR(50) NOT NULL,
    `PASSWORD` VARCHAR(200) NOT NULL,
    `NICKNAME` VARCHAR(200) NOT NULL,
    `REFRESH_TOKEN` VARCHAR(256),
    `LOGIN_TYPE` VARCHAR(50) NOT NULL DEFAULT 'DEFAULT'
);

CREATE TABLE `OAUTH` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `MEMBER_ID` BIGINT NOT NULL,
    `ACCESS_TOKEN` VARCHAR(256),
    `REFRESH_TOKEN` VARCHAR(256),
    `PROVIDER` VARCHAR(256)
);

CREATE TABLE `ACCOMMODATION` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `HOST_ID` BIGINT,
    `TITLE` VARCHAR(50) NOT NULL,
    `PLACE_CATEGORY` VARCHAR(50) NOT NULL,
    `BASE_PRICE_PER_NIGHT` BIGINT NOT NULL,
    `DESCRIPTION` VARCHAR(500),
    `MAX_GUEST_COUNT` INT NOT NULL,
    `MAX_INFANT_COUNT` INT NOT NULL,
    `BEDROOM_COUNT` INT NOT NULL,
    `BED_COUNT` INT NOT NULL,
    `BATHROOM_COUNT` INT NOT NULL,
    `CHECK_IN_TIME` TIME NOT NULL DEFAULT '16:00:00',
    `CHECK_OUT_TIME` TIME NOT NULL DEFAULT '11:00:00',
    `COUNTRY` VARCHAR(2) NOT NULL,
    `PROVINCE` VARCHAR(100) NOT NULL,
    `CITY` VARCHAR(100),
    `DISTRICT` VARCHAR(100) NOT NULL,
    `STREET_ADDRESS` VARCHAR(100) NOT NULL,
    `STREET_ADDRESS_DETAIL` VARCHAR(100),
    `POSTAL_CODE` VARCHAR(50),
    `COORDINATE` POINT SRID 4326 NOT NULL
);

CREATE TABLE `AMENITY` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `NAME` VARCHAR(50) NOT NULL
);

CREATE TABLE `ACCO_AMEN` (
     `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
     `ACCO_ID` BIGINT NOT NULL,
     `AMEN_ID` BIGINT NOT NULL
);

CREATE TABLE `ACCO_IMAGE` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ACCO_ID` BIGINT,
    `URL` VARCHAR(500) NOT NULL
);

CREATE TABLE `RESERVATION` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `MEMBER_ID` BIGINT NOT NULL,
    `CREATED_AT` TIMESTAMP NOT NULL,
    `ADULT_COUNT` INT NOT NULL,
    `CHILD_COUNT` INT NOT NULL,
    `INFANT_COUNT` INT NOT NULL,
    `CHECK_IN_DATE` DATE NOT NULL,
    `CHECK_OUT_DATE` DATE NOT NULL,
    `FINAL_PRICE` BIGINT NOT NULL,
    `STATUS` TEXT NOT NULL
);

CREATE TABLE `ACCO_PRODUCT` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ACCO_ID` BIGINT NOT NULL,
    `RESERVE_DATE` DATE NOT NULL,
    `PRICE` BIGINT NOT NULL,
    `IS_RESERVED` bool NOT NULL DEFAULT false,
    `CREATED_AT` TIMESTAMP NOT NULL,
    `MODIFIED_AT` TIMESTAMP
);

CREATE TABLE `RESERVATION_PRODUCT` (
    `RESERVE_ID` BIGINT NOT NULL,
    `PRODUCT_ID` BIGINT NOT NULL,
    PRIMARY KEY (`RESERVE_ID`, `PRODUCT_ID`)
);

CREATE UNIQUE INDEX `ACCO_PRODUCT_index_0` ON `ACCO_PRODUCT` (`ACCO_ID`, `RESERVE_DATE`);

ALTER TABLE `ACCO_AMEN` ADD FOREIGN KEY (`ACCO_ID`) REFERENCES `ACCOMMODATION` (`ID`);

ALTER TABLE `ACCO_AMEN` ADD FOREIGN KEY (`AMEN_ID`) REFERENCES `AMENITY` (`ID`);

ALTER TABLE `ACCOMMODATION` ADD FOREIGN KEY (`HOST_ID`) REFERENCES `MEMBER` (`ID`);

ALTER TABLE `ACCO_IMAGE` ADD FOREIGN KEY (`ACCO_ID`) REFERENCES `ACCOMMODATION` (`ID`);

ALTER TABLE `RESERVATION` ADD FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`ID`);

ALTER TABLE `RESERVATION_PRODUCT` ADD FOREIGN KEY (`RESERVE_ID`) REFERENCES `RESERVATION` (`ID`);

ALTER TABLE `RESERVATION_PRODUCT` ADD FOREIGN KEY (`PRODUCT_ID`) REFERENCES `ACCO_PRODUCT` (`ID`);

ALTER TABLE `ACCO_PRODUCT` ADD FOREIGN KEY (`ACCO_ID`) REFERENCES `ACCOMMODATION` (`ID`);

ALTER TABLE `OAUTH` ADD FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`ID`);