name: Docker 기반 CI/CD 구축하기

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repo에서 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 테스트 및 빌드하기
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정하기
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t airdnb-server .

      - name: Docker 이미지에 Tag 붙이기
        run: |
          docker tag airdnb-server ${{ steps.login-ecr.outputs.registry }}/airdnb-server:latest

      - name: ECR에 Docker 이미지 Push 하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/airdnb-server:latest

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker stop airdnb-server || true
            docker rm airdnb-server || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/airdnb-server:latest
            docker run -d --name airdnb-server -p 8080:8080 \
            -e SPRING_DATASOURCE_URL=${{ secrets.RDS_ENDPOINT }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.RDS_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            ${{ steps.login-ecr.outputs.registry }}/airdnb-server:latest
