name: Docker Compose run

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name : JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: create properties
        run: touch ./BE/airdnb/src/main/resources/application.yml
      - run: echo "${{ secrets.APPLICATION }}" > ./BE/airdnb/src/main/resources/application.yml
        shell: bash

      - name: grant gradlew
        run: |
          cd ./BE/airdnb
          chmod +x ./gradlew

      - name: Build with gradle
        run: |
          cd ./BE/airdnb
          ./gradlew clean build -x test

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image Processing
        run: |
          cd ./BE/airdnb
          docker build -t seondays/airdnb:latest .
          docker push seondays/airdnb:latest

      - name: SSH Processing
        uses: appleboy/ssh-action@v0.1.6
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          script: |
            sudo docker pull seondays/airdnb:latest
            sudo docker-compose down
            sudo docker-compose up -d
