name: CI/CD Backend Pipeline

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Make application.yaml
        run: |
          cd ./airdnb/src/main
          mkdir -p resources
          cd resources
          touch application.yaml
          echo "${{ secrets.EC2_YAML }}" > application.yaml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Grant execute permission for gradlew
        run: |
          cd ./airdnb
          chmod +x gradlew

      - name: Build with Gradle
        run: |
          cd ./airdnb
          ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_ID }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}

      - name: Docker build & push to Docker repo
        run: |
          cd ./airdnb
          docker build -t ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_HUB_NAME }}:latest .
          docker push ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_HUB_NAME }}:latest

      - name: Deploy to Prod Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu
            sudo ./deploy_server.sh -y
