name: Java + SpringBoot project CI/CD with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout codes
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Make application.yml
      run: |
        cd ./src/main/resources
        touch application-dev.yml
        echo "${{ secrets.DEV_YML }}" > application-dev.yml
        touch application-oauth.yml
        echo "${{ secrets.OAUTH_YML }}" > application-oauth.yml
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.1.0

    - name: Set execution authority gradle wrapper
      run: chmod +x ./gradlew

    - name: Clean Build with Gradle Wrapper without test
      run: ./gradlew clean build -x test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: LogIn to DockerHub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USER_ID }}
        password: ${{ secrets.DOCKER_USER_PASSWORD }}

    - name: Docker build & push to Docker repo
      run: |
        docker build -t ${{ secrets.DOCKER_USER_ID }}/${{ secrets.DOCKER_HUB_NAME }}:latest .
        docker push ${{ secrets.DOCKER_USER_ID }}/${{ secrets.DOCKER_HUB_NAME }}:latest

    - name: Deploy to Prod Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker-compose stop springboot
          sudo docker-compose rm -f springboot
          echo ${{ secrets.DOCKER_USER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER_ID }} --password-stdin
          sudo docker-compose pull ${{ secrets.DOCKER_USER_ID }}/${{ secrets.DOCKER_HUB_NAME }}:latest
          sudo docker-compose up -d --no-deps springboot
